// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAepo9IANiMViM6x9OT9vcT_kn18xJlKlc',
    appId: '1:850447987711:web:341b76cc904d2e7f00edca',
    messagingSenderId: '850447987711',
    projectId: 'fcmflutter-f115d',
    authDomain: 'fcmflutter-f115d.firebaseapp.com',
    storageBucket: 'fcmflutter-f115d.appspot.com',
    measurementId: 'G-ZN26704NCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm6SwZBNLNlTJ4KJjb2Ke2Ls87A_TwUuQ',
    appId: '1:850447987711:android:caaebffb153ceca600edca',
    messagingSenderId: '850447987711',
    projectId: 'fcmflutter-f115d',
    storageBucket: 'fcmflutter-f115d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjIVAywb17hdnVMMX_4sJ1m8SPFWVthf0',
    appId: '1:850447987711:ios:83b76b984d0ed29400edca',
    messagingSenderId: '850447987711',
    projectId: 'fcmflutter-f115d',
    storageBucket: 'fcmflutter-f115d.appspot.com',
    iosBundleId: 'com.example.fcmapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjIVAywb17hdnVMMX_4sJ1m8SPFWVthf0',
    appId: '1:850447987711:ios:b232e1de138f457a00edca',
    messagingSenderId: '850447987711',
    projectId: 'fcmflutter-f115d',
    storageBucket: 'fcmflutter-f115d.appspot.com',
    iosBundleId: 'com.example.fcmapp.RunnerTests',
  );
}
